= Batch email notifications

Batch email notifications feature allows to send multiple notifications in a unique email.
This is useful for grouping notifications and not overloading your users emails.

Notifications are sent in groups, sorted from the most recent notifications.

Notifications that have not been sent after a certain time are not sent at all. This means that your users have already received plenty of them and will already have to visit the platform.

Deleting a notification cancels the future associated email.

This is based on 3 parameters:

- `batch_email_notifications_enabled`: Enable batch email notifications and disable single email notification (default to false)

- `batch_email_notifications_expired`: period of time after which a notification is considered to have expired (default to 1 week)

- `batch_email_notifications_max_length`: Number of notifications to send in the same email (default to 10)

== How to setup?

=== Setup using initializers

In `config/initialize/decidim.rb`, configure the batch notifications as below

[source,ruby]
----
config.batch_email_notifications_enabled = true
config.batch_email_notifications_expired = 1.week
config.batch_email_notifications_max_length = 10
----

=== Setup using ENV variables

Those 3 configurations are using ENV variable if you do not want to configure the batch notifications using initializers.

`batch_email_notifications_enabled` = ENV["BATCH_NOTIFICATIONS_ENABLED"]
`batch_email_notifications_max_length` = ENV["BATCH_NOTIFICATIONS_LIMIT"]

`batch_email_notifications_expired` is not configurable from ENV variables for now.

=== Server setup

Batch email notification required to execute a rake task ("rake decidim:batch_email_notifications:send") at regular intervals.

1. Cron setup

Use `crontab -e` and enter the following lines:

[source,shell]
----
0 */3 * * * cd {MY_APP} && {/path/to/bundle} exec rake decidim:batch_email_notifications:send
----

You could find the documentation about cron on https://www.man7.org/linux/man-pages/man8/cron.8.html[cron man page]

1. Heroku scheduler

You can find information on how to setup heroku scheduler on https://devcenter.heroku.com/articles/scheduler[heroku documentation]

1. Sidekiq scheduler

In `config/sidekiq.yml`

[source,ruby]
----
# sidekiq_scheduler.yml

batch_email_notifications:
  every: ['3h', first_in: '1m']
  class: Decidim::BatchEmailNotificationsGeneratorJob
  queue: scheduled
  description: 'This job executes batch email notifications'
----
